### ISSUE TITLE
Hello From HashiCorp Vault team

### ISSUE THREAD

**Issue by narayan-iyengar** [gitirabassi/vault-plugin-secrets-wireguard#2]
Hi,
This is not really an issue. I am from the HashiCorp Vault team looking to do some interviews with plugin developers. I saw some of your livecast when you were developing the wireguard vault plugin and wanted to just chat about your experience in writing a plugin.

this is regarding some new features we are planning on introducing in future releases.
Would you be willing to meet some time this week or next week?

Thanks in advance!!

**Comment by phisco** [comment]
Hi, sure! 
Feel free to add me and Giacomo on twitter ([@Phisc0](https://twitter.com/Phisc0) and [@gitirabassi](https://twitter.com/gitirabassi)) to organize this better!

**Comment by phisco** [comment]
Hi, sure!
Feel free to add Giacomo and me on twitter ([@gitirabassi](https://twitter.com/gitirabassi) and [@Phisc0](https://twitter.com/Phisc0)) to organize this better!

**Comment by narayan-iyengar** [comment]
I sent both of you a DM on twitter (from username @random_copy)
I am at narayan [at] hashicorp and can meet sometime next week to chat and learn about your experience with writing Vault plugins!!
