### ISSUE TITLE
Add WIP disclaimer in README

### ISSUE THREAD

**Issue by Legogris** [gitirabassi/vault-plugin-secrets-wireguard#3]
Hey guys, really nice idea for a project - just want to check if this was more of a one-off hackathon thing or if it's something you aim to continue working on?

(AFAICT it's only half-way to working; only static placeholder values are returned from supposedly dynamic endpoints)

In either case, it would be great to add a disclaimer about the status at the top of the README so people who discover the repo know what to expect.

Cheers

**Comment by gitirabassi** [comment]
I've added a disclaimer now
